/// <reference path="../../apps/web/lib/supabase/types.d.ts" />

import type { UploadManifest } from './speech-sample-upload.mts';
import type {
  SampleCatalog,
  SampleManifest,
  SampleVoice,
} from './speech-samples.mts';
import { UUID_PATTERN } from './uuid.mts';

type VoiceMetadata = Pick<
  Tables<'voices'>,
  | 'user_id'
  | 'description'
  | 'feature'
  | 'is_nsfw'
  | 'is_public'
  | 'type'
  | 'sort_order'
>;
export interface CatalogVoice extends SampleVoice {
  row: VoiceMetadata;
  sourceIds: string[];
}
export interface VoiceCatalog extends SampleCatalog {
  folder: string;
  publicUrl: string;
  voices: CatalogVoice[];
}

function sql(value: string | number | boolean | null): string {
  if (value === null) return 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (typeof value === 'number') {
    if (!Number.isSafeInteger(value))
      throw new Error('Expected integer SQL value');
    return String(value);
  }
  if (typeof value !== 'string' || value.includes('\0'))
    throw new Error('Invalid SQL string');
  return `'${value.replaceAll("'", "''")}'`;
}

export function prepareVoiceCatalogSql(
  catalog: VoiceCatalog,
  options: {
    draft?: boolean;
    generated?: SampleManifest;
    uploads?: UploadManifest;
  },
): string {
  const { draft = false, generated, uploads } = options;
  if (
    !draft &&
    (!(generated && uploads) ||
      uploads.failures.length ||
      generated.failures.length)
  )
    throw new Error(
      'Final SQL requires complete generation and verified uploads',
    );
  const ids = new Set<string>();
  const identities = new Set<string>();
  const statements = catalog.voices.map((voice) => {
    if (!(UUID_PATTERN.test(voice.id) && UUID_PATTERN.test(voice.row.user_id)))
      throw new Error('Invalid catalog UUID');
    if (voice.row.feature !== 'tts') throw new Error('Expected a TTS voice');
    const identity = JSON.stringify([
      voice.name,
      voice.language,
      voice.row.user_id,
    ]);
    if (ids.has(voice.id) || identities.has(identity))
      throw new Error('Duplicate catalog entry');
    ids.add(voice.id);
    identities.add(identity);
    const key =
      catalog.folder === '.'
        ? voice.filename
        : `${catalog.folder}/${voice.filename}`;
    const url = new URL(key, `${catalog.publicUrl}/`).href;
    if (!draft) {
      const sample = generated?.samples.find((item) => item.id === voice.id);
      const upload = uploads?.verified.find((item) => item.id === voice.id);
      if (
        !(sample && upload) ||
        upload.sha256 !== sample.sha256 ||
        upload.filename !== voice.filename ||
        upload.key !== key ||
        upload.url !== url
      )
        throw new Error(`Missing verified upload for ${voice.name}`);
      for (const field of [
        'name',
        'filename',
        'text',
        'style',
        'language',
      ] as const) {
        if (sample[field] !== voice[field])
          throw new Error(
            `Generated sample differs from catalog: ${voice.name}`,
          );
      }
    }
    const fields = [
      'id',
      'user_id',
      'name',
      'model',
      'language',
      'feature',
      'type',
      'description',
      'sample_prompt',
      'sample_url',
      'is_public',
      'is_nsfw',
      'sort_order',
    ];
    const values = [
      voice.id,
      voice.row.user_id,
      voice.name,
      'gpro38',
      voice.language,
      'tts',
      voice.row.type,
      voice.row.description,
      voice.text,
      url,
      voice.row.is_public,
      voice.row.is_nsfw,
      voice.row.sort_order,
    ];
    return `INSERT INTO public.voices (${fields.join(', ')})\nSELECT ${values.map(sql).join(', ')}\nWHERE NOT EXISTS (\n  SELECT 1 FROM public.voices\n  WHERE model = 'gpro38' AND name = ${sql(voice.name)}\n    AND language = ${sql(voice.language)} AND user_id = ${sql(voice.row.user_id)}::uuid\n)\nON CONFLICT (id) DO NOTHING;`;
  });
  return [
    '-- Additive Gemini 3.8 catalog. Deploy gpro38 support before generating with these voices.',
    '-- Generated by prepare-gemini-voice-sql. Existing voices are preserved.',
    'BEGIN;',
    'SET LOCAL standard_conforming_strings = on;',
    ...(draft
      ? [
          "DO $$ BEGIN RAISE EXCEPTION 'DRAFT: listen to samples, upload, then regenerate SQL with verified uploads'; END $$;",
        ]
      : []),
    ...statements,
    'COMMIT;\n',
  ].join('\n\n');
}
