name: Deploy Telegram Bot

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/supabase/functions/telegram-bot/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Install deployctl
        run: deno install -gArf jsr:@deno/deployctl

      - name: Deploy to Deno Deploy
        working-directory: apps/web/supabase/functions/telegram-bot
        run: deployctl deploy --project=sv-telegram-bot --entrypoint=./index.ts --prod --token=$DENO_TOKEN
        env:
          DENO_TOKEN: ${{ secrets.DENO_TOKEN }}
