name: unlighthouse

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  unlighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install unlighthouse dependencies
        run: npm install -g @unlighthouse/cli puppeteer

      - name: Build the project
        env:
          KV_URL: ${{ secrets.KV_URL }}
          KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
          KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
          KV_REST_API_READ_ONLY_TOKEN: ${{ secrets.KV_REST_API_READ_ONLY_TOKEN }}
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          NEXT_PUBLIC_CRISP_WEBSITE_ID: ${{ secrets.NEXT_PUBLIC_CRISP_WEBSITE_ID }}
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.REPLICATE_API_TOKEN }}
        run: pnpm run build
        
      - name: Serve the project
        run: pnpm run start &

      - name: Wait for the start to be ready
        run: |
          timeout 60s bash -c 'until echo > /dev/tcp/localhost/3000; do sleep 1; done'

      - name: Run Unlighthouse CI
        run: unlighthouse-ci --site "http://localhost:9000" --budget 90 --reporter "jsonExpanded" --mobile --urls /

      - name: Read Lighthouse Result
        run: cat ./.unlighthouse/ci-result.json

      - name: Terminate start process
        run: pkill -f "pnpm run start"
